### ISSUE TITLE
Bug: YUI js compressor fails to compress holderjs

### ISSUE THREAD

**Issue by rajibahmed** [imsky/holder#121]
Hello,

I am using assetic php yui js filter to compressing external libs.
It can compress all other libs beside holderjs. 
When I include holderjs it fails like this.

//Best

```
 [Assetic\Exception\FilterException]
  An error occurred while running:
  '/usr/bin/java' '-jar' '/usr/local/bin/yuicompressor.jar' '-o' '/private/var/folders/2k/bgr3y08x4_9532x373z8sc1c0000gn/T/YUI-OUT-5SSaUV' '--type' 'js' '/private/var/folders/2k/bgr3y08x4_9532x373z8sc1c0000gn/T/YUI-IN-8QzOCA'
  Error Output:
  [ERROR] 12:3977:missing name after . operator
  [ERROR] 1:0:Compilation produced 1 syntax errors.
  org.mozilla.javascript.EvaluatorException: Compilation produced 1 syntax errors.
  	at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:154)
  	at org.mozilla.javascript.Parser.parse(Parser.java:392)
  	at org.mozilla.javascript.Parser.parse(Parser.java:337)
  	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:312)
  	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:533)
  	at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:131)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:483)
  	at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
  Input:
  /*!
  Holder - client side image placeholders
  Version 2.4.1+f2l1h
  © 2014 Ivan Malopinsky - http://imsky.co
  Site:     http://imsky.github.io/holder
  Issues:   https://github.com/imsky/holder/issues
  License:  http://opensource.org/licenses/MIT
  */
```

**Comment by imsky** [comment]
Since this seems to be related to the third party `getComputedStyle` polyfill included in Holder, I've taken it out. Let me know if YUI errors out on another part of code.
